# Generated by Django 6.0.2 on 2026-02-18 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('event_type', models.CharField(choices=[('masterclass', 'Master-klass'), ('hackathon', 'Xakaton'), ('lecture', "Ma'ruza"), ('competition', 'Tanlov')], default='masterclass', max_length=20, verbose_name='Turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('date', models.DateTimeField(verbose_name='Sana va vaqt')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Joy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikonka')),
                ('image', models.ImageField(blank=True, null=True, upload_to='labs/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laboratoriya',
                'verbose_name_plural': 'Laboratoriyalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('is_published', models.BooleanField(default=False, verbose_name='Chop etilgan')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Chop etilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logotip')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Yoshlar innovatsiya markazi', max_length=200, verbose_name='Sayt nomi')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logotip')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Favicon')),
                ('slogan', models.CharField(default="Kelajak texnologiyalari — yoshlar qo'lida", max_length=300, verbose_name='Slogan')),
                ('about_text', models.TextField(blank=True, verbose_name='Markaz haqida matn')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram havola')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram havola')),
                ('youtube_link', models.URLField(blank=True, verbose_name='YouTube havola')),
                ('map_embed', models.TextField(blank=True, verbose_name='Xarita embed kodi')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='Ish vaqti')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('level', models.CharField(choices=[('beginner', "Boshlang'ich"), ('advanced', "Ilg'or")], default='beginner', max_length=20, verbose_name='Daraja')),
                ('age_min', models.PositiveIntegerField(default=10, verbose_name='Minimal yosh')),
                ('age_max', models.PositiveIntegerField(default=25, verbose_name='Maksimal yosh')),
                ('format', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('hybrid', 'Gibrid')], default='offline', max_length=20, verbose_name='Format')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Davomiylik')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='dashboard.laboratory', verbose_name='Laboratoriya')),
            ],
            options={
                'verbose_name': 'Dastur',
                'verbose_name_plural': 'Dasturlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('certificate_id', models.CharField(max_length=50, unique=True, verbose_name='Sertifikat ID')),
                ('issued_date', models.DateField(verbose_name='Berilgan sana')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='PDF fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='dashboard.program', verbose_name='Dastur')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='dashboard.program', verbose_name='Dastur')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('stage', models.CharField(choices=[('idea', "G'oya"), ('prototype', 'Prototip'), ('mvp', 'MVP')], default='idea', max_length=20, verbose_name='Bosqich')),
                ('team_members', models.TextField(blank=True, verbose_name="Jamoa a'zolari")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
